/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("APIApi", () => {
  let instance: api.APIApi
  beforeEach(function() {
    instance = new api.APIApi(config)
  });

  test("deleteAPIDeleteFile", () => {
    const fileId: number = 56
    return expect(instance.deleteAPIDeleteFile(fileId, {})).resolves.toBe(null)
  })
  test("getAPIAllRecords", () => {
    return expect(instance.getAPIAllRecords({})).resolves.toBe(null)
  })
  test("getAPIOneRecord", () => {
    const fileId: number = 56
    return expect(instance.getAPIOneRecord(fileId, {})).resolves.toBe(null)
  })
  test("postAPILoadFile", () => {
    return expect(instance.postAPILoadFile({})).resolves.toBe(null)
  })
  test("postAPIMakePredictions", () => {
    const fileId: number = 56
    const body: api.PredictionRequest1 = undefined
    return expect(instance.postAPIMakePredictions(fileId, body, {})).resolves.toBe(null)
  })
  test("putAPISetTu", () => {
    const fileId: number = 56
    const body: api.SetTURequest1 = undefined
    return expect(instance.putAPISetTu(fileId, body, {})).resolves.toBe(null)
  })
})

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("getgreet", () => {
    return expect(instance.getgreet({})).resolves.toBe(null)
  })
})

